trigger:
  branches:
    include:
    - main
    - release/*

pool:
  vmImage: 'windows-latest'

stages:
- template: jobTemplates\build.yml


- stage: DeployToDev
  variables:
  - template: variableTemplates\dev.yml
  - template: variableTemplates\shared.yml
  jobs:
  - template: jobTemplates\deploy.yml
    parameters:
      AzureServiceConnection: 's255d.azdo.deployment'
      Environment: Dev

- stage: DeployToTest
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables:
  - template: variableTemplates\test.yml
  - template: variableTemplates\shared.yml
  jobs:
  - template: jobTemplates\deploy.yml
    parameters:
      AzureServiceConnection: 's255t.azdo.deployment'
      Environment: Test

- stage: DeployToPreProd
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables:
  - template: variableTemplates\preprod.yml
  - template: variableTemplates\shared.yml
  jobs:
  - template: jobTemplates\deploy.yml
    parameters:
      AzureServiceConnection: 's255t.azdo.deployment'
      Environment: PreProduction

- stage: DeployToDataScience
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables:
  - template: variableTemplates\datasci.yml
  - template: variableTemplates\shared.yml
  jobs:
  - template: jobTemplates\deploy.yml
    parameters:
      AzureServiceConnection: 's255t.azdo.deployment'
      Environment: DataScience

- stage: DeployToProduction
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables:
  - template: variableTemplates\prod.yml
  - template: variableTemplates\shared.yml
  jobs:
  - template: jobTemplates\deploy.yml
    parameters:
      AzureServiceConnection: 's255p.azdo.deployment'
      Environment: Production
